spring.application.name: boxfish-online-card-timer
logging:
  level:
    com:
      boxfishedu: debug
    org:
      springframework: info
  file: ${user.home}/logs/${spring.application.name}.log

##################接口调用地址
interface:
  address:
    teacher_service: http://101.201.237.252:8099
    course_recommended_service: http://101.201.237.252:8083
    fishcard_service: http://127.0.0.1:8080
    order_service: http://101.201.237.252:8082
    course_online_service: http://101.201.239.116:9090

server:
  port: 9997

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  test-while-idle: true
  validation-query: SELECT 1
  initial-size: 1
  max-active: 2
  max-idle: 1
  connection-timeout: 5000

spring:
  profiles:
#   active: test_extranet
   active: development
#   active: product
#   active:  pretest

---
spring:
  datasource:
    url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com:3306/service?useUnicode=true&characterEncoding=utf8
    username: service
    password: Box123456
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-while-idle: true
  mail:
    host: smtpdm.aliyun.com
    port: 25
    username: nobody@send.boxfish.cn
    password: Boxfish123
    tousers: huchunlinnk@163.com,huchunlinnk14@163.com
  rabbitmq:
    host: 192.168.77.91
    port: 5672
    address: 101.201.239.116:5672
    username: boxfish
    password: boxfish
    virtualHost: local
  profiles: test_extranet

---
spring:
  datasource:
    url: jdbc:mysql://boxfish2016inside.mysql.rds.aliyuncs.com:3306/service_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com:3306/service_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: service
    password: Box123456
  mongo:
    serverAddress: 123.56.13.168:27017
    dbName: fishcard
    username: root
    password: Boxfish2016
  redis:
    hostName: 8619f2f4a93c4a70.m.cnbja.kvstore.aliyuncs.com
    password: Box12345678
    port: 6379
    timeout: 10000
  rabbitmq:
    address: 127.0.0.1:5672
#    port: 5672
    username: admin
    password: boxfish123
    virtualHost: local
  mail:
    host: smtpdm.aliyun.com
    port: 25
    username: nobody@send.boxfish.cn
    password: Boxfish123
    tousers: huchunlinnk@163.com,huchunlinnk14@163.com
  profiles: test

---
spring:
  datasource:
    url: jdbc:mysql://boxfish2016inside.mysql.rds.aliyuncs.com:3306/service_foreign?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com:3306/service_foreign?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: service
    password: Box123456
  mongo:
    serverAddress: 127.0.0.1:27017
    dbName: fishcard
    username: root
    password: Boxfish2016
  redis:
    hostName: 8619f2f4a93c4a70.m.cnbja.kvstore.aliyuncs.com
    password: Box12345678
    port: 6379
    timeout: 10000
  rabbitmq:
    address: 127.0.0.1:5672
#    port: 5672
    username: admin
    password: boxfish123
    virtualHost: local
  mail:
    host: smtpdm.aliyun.com
    port: 25
    username: nobody@send.boxfish.cn
    password: Boxfish123
    tousers: huchunlinnk@163.com,huchunlinnk14@163.com
  profiles: pretest

---
spring:
  datasource:
    url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com:3306/service?useUnicode=true&characterEncoding=utf8
    username: service
    password: Box123456
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
  mail:
    host: smtpdm.aliyun.com
    port: 25
    username: nobody@send.boxfish.cn
    password: Boxfish123
    tousers: 393269748@qq.com
  rabbitmq:
    address: 101.201.239.116
#    port:5672
    username: boxfish
    password: boxfish
    virtualHost: local
  profiles: development

---
spring:
  datasource:
    url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com:3306/service?useUnicode=true&characterEncoding=utf8
    username: service
    password: Box123456
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
  mail:
    host: smtpdm.aliyun.com
    port: 25
    username: nobody@send.boxfish.cn
    password: Boxfish123
    tousers: 393269748@qq.com
  rabbitmq:
    address: 127.0.0.1
#    port:5672
    username: boxfish
    password: boxfish
    virtualHost: local
  profiles: development_new

#================================================================生产环境===========================================================#
---
spring:
  datasource:
    url: jdbc:mysql://boxfish-online-2016-inside.mysql.rds.aliyuncs.com:3306/service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: service
    password: nEaJiP7hwoXEUkPDnDjaBK3hEJanHTec
  mongo:
    serverAddress: dds-bp1d8c5924fd01641.mongodb.rds.aliyuncs.com:3717
    dbName: fishcard
    username: root
    password: sp3JDgEQKPXXshJBFPi8bbFfzbTGMtVc
  redis:
    hostName: 96cbdee519414aba.m.cnhza.kvstore.aliyuncs.com
    password: kVxowYcWE6NdfKAP6zDhxZsZgkPGuC
    port: 6379
    timeout: 10000
  rabbitmq:
    address: 192.168.1.19:5672,192.168.1.18:5672,120.27.227.72:5672
#    host: 123.56.11.39
#    port: 5672
    username: admin
    password: boxfish123
    virtualHost: local
  mail:
    host: smtpdm.aliyun.com
    port: 25
    username: nobody@send.boxfish.cn
    password: Boxfish123
    tousers: huchunlin@boxfish.cn,fenglei@boxfish.cn,suhaijiang@boxfish.cn,jiaozijun@boxfish.cn
  profiles: product