spring.application.name: boxfish-online-card-health
logging:
  level:
    com:
      boxfishedu: debug
    org:
      springframework: info
  file: ${user.home}/logs/${spring.application.name}.log


spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
server.compression.enabled: true
server.compression.mime-types: "text/html,text/xml,text/plain,text/html,text/css,application/json"

spring.mvc.view.prefix: /health/
spring.mvc.view.suffix: .html

#spring.profiles.active: product
spring.profiles.active: test


#===============================================================test环境:123.56.13.168 机器密码:Boxfish98765===============================================================
#===============================================================redis-cli -h 123.56.13.168 -p 6379 -a Box12345678
#===============================================================mongo  mongo --host 123.56.13.168:27017 --authenticationDatabase fishcard -u root -p Boxfish2016========
---
spring:
  profiles: test

##################接口调用地址
interface:
  address:
    fishcard_service: http://123.56.13.168:8080/fishcard

server:
  port: 10000
  servlet-path: /health

#===============================================================生产环境===============================================================
#=============192.168.1.30===============192.168.1.29======================192.168.1.25===============================================#
#=============redis-cli -h 96cbdee519414aba.m.cnhza.kvstore.aliyuncs.com -p 6379 -a kVxowYcWE6NdfKAP6zDhxZsZgkPGuC
#=================mongo:    mongo --host dds-bp1d8c5924fd01642.mongodb.rds.aliyuncs.com:3717 --authenticationDatabase admin -u root -p sp3JDgEQKPXXshJBFPi8bbFfzbTGMtVc
#=================外网mq:   120.27.227.72:5672(映射:120.27.227.72:5672)================================================================#
---
spring:
  profiles: product

##################接口调用地址
interface:
  address:
    fishcard_service: http://online-api.boxfish.cn/fishcard

server:
  port: 10000
  servlet-path: /health
